# Generated by Django 2.2.4 on 2019-08-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smorandev', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield'),
        ),
    ]
