# Generated by Django 2.2.4 on 2019-08-14 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smorandev', '0002_auto_20190813_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='blurb',
        ),
    ]
