# Generated by Django 2.2.4 on 2019-08-14 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smorandev', '0003_remove_project_blurb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_detail',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
    ]
