# Generated by Django 2.2.4 on 2019-08-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smorandev', '0004_auto_20190813_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='blurb',
            field=models.TextField(default='Sample text', verbose_name='Blurb'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.TextField(default='https://s3.us-east-2.amazonaws.com/smoran.dev/images/default.png', verbose_name='Image Link'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_detail',
            field=models.TextField(default='Description', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.TextField(default='Python, probably'),
        ),
    ]
