# Generated by Django 2.1.5 on 2019-08-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smorandev', '0005_auto_20190813_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='webgl_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
