# Generated by Django 2.2.3 on 2019-08-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smorandev', '0006_project_webgl_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_size',
            field=models.TextField(default='col-md-4'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
