# Generated by Django 2.2.4 on 2019-08-23 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smorandev', '0007_auto_20190814_2147'),
        ('smorandev', '0007_auto_20190821_1340'),
    ]

    operations = [
    ]
