# Generated by Django 2.2.4 on 2019-08-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smorandev', '0008_merge_20190823_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='webgl_fshader',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Fragment Shader'),
        ),
        migrations.AddField(
            model_name='project',
            name='webgl_vshader',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Vertex Shader'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
