# Generated by Django 3.0.4 on 2020-03-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smorandev', '0011_project_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='markdown',
            field=models.BooleanField(default=False),
        ),
    ]
